name = "datesl"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "sithumina-db"
database_id = "YOUR_DATABASE_ID" # User to replace this

[[r2_buckets]]
binding = "R2"
bucket_name = "sithumina-assets"

[ai]
binding = "AI"
