name = "matchlk"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "datesl-db"
database_id = "6bb2be2a-5ed4-47bd-93f3-6a140869c0a0"



[[r2_buckets]]
binding = "R2"
bucket_name = "datesl-assets"

[ai]
binding = "AI"
